import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner";
import Latest from "@/components/mainComponents/book";
import Categories from "@/components/mainComponents/categories";
import Featured from "@/components/mainComponents/featured";
import Gift from "@/components/mainComponents/gift";
import Works from "@/components/mainComponents/works";
import Footer from "@/components/mainComponents/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Muhammad Fahad Siddiqu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner />
        <Latest />
        <Categories/>
        <Featured/>
        <Gift/>
        <Works/>
        <Footer/>
      </main>
    </>
  );
}
